### ISSUE TITLE
Some issues with data preparation

### ISSUE THREAD

**Issue by Xccc0304** [mindflow-institue/DermoSegDiff#3]
Inside of this folder the required numpy files will create inside of <np> folder. 
Does this sentence mean to convert the images and Groundtruth into numpy format data and then put them in the same folder?

**Comment by tobi-ore** [comment]
When you run training.py, it checks for an np folder in the data_dir for the X and Y in .npy. However, the code is written so that if the numpy file does not exist, it checks the training_input and ground_truth folder for the .jpg or .png files and converts them all to a .npy file X and Y respectively, then save it in a folder called np in the data_dir.

**Comment by bravo-hq** [comment]
@ChaiJinhao Has the issue you encountered been satisfactorily addressed through the solution provided by @tobi-ore?
